CREATE DATABASE BDI;
USE BDI;

CREATE TABLE PESSOA (
	PES_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	PES_NOME VARCHAR(60) NOT NULL, 
	PES_CPF VARCHAR(11) NOT NULL UNIQUE,
    PES_EMAIL1 VARCHAR(100) DEFAULT '' NOT NULL,
    PES_EMAIL2 VARCHAR(100),
    PES_LOGIN_PASSWORD BLOB,
	PES_SEXO VARCHAR(1) NOT NULL, 
	PES_DATA_NASC DATE NOT NULL, 
    PES_FOTO LONGBLOB
);

CREATE TABLE FUNCIONARIO (
	FUNC_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	FUNC_DATA_ADMISSAO DATE NOT NULL,
	FUNC_DATA_DESLIGAMENTO DATE,
	FUNC_PIS VARCHAR(15), 
	FUNC_CNH VARCHAR(11),
    FUNC_ID_PESSOA INTEGER NOT NULL UNIQUE,
	CONSTRAINT FK_FUNC_PESSOA FOREIGN KEY(FUNC_ID_PESSOA) REFERENCES PESSOA(PES_ID)
);

CREATE TABLE PRATICANTE (
	PRAT_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRAT_ID_PESSOA INTEGER NOT NULL UNIQUE,
    PRAT_ALTURA FLOAT NOT NULL,
    PRAT_PESO FLOAT NOT NULL,
    CONSTRAINT FK_PRAT_PESSOA FOREIGN KEY(PRAT_ID_PESSOA) REFERENCES PESSOA(PES_ID)
);

CREATE TABLE ANIMAL (
	ANI_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	ANI_IDADE INTEGER, 
    ANI_NOME VARCHAR(60) NOT NULL, 
	ANI_PORTE VARCHAR(2) NOT NULL,
    ANI_COMPORTAMENTO VARCHAR(60),
    ANI_ANDADURA VARCHAR(60)
);

CREATE TABLE ATIVIDADE (
	ATV_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	ATV_DESCRICAO VARCHAR(100) NOT NULL, 
	ATV_DURACAO INTEGER NOT NULL
);

CREATE TABLE MATERIAL (
	MAT_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	MAT_DESCRICAO VARCHAR(60) NOT NULL
);

CREATE TABLE SESSAO (
	SES_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SES_DESCRICAO VARCHAR(200),
    SES_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE SESSAOXPRATICANTE (
	SXP_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SXP_COD_SESSAO INTEGER NOT NULL,
    SXP_COD_PRATICANTE INTEGER NOT NULL,
	CONSTRAINT FK_SXP_REF_SESSAO FOREIGN KEY(SXP_COD_SESSAO) REFERENCES SESSAO(SES_ID)  ON DELETE CASCADE,
    CONSTRAINT FK_SXP_REF_PRATICANTE FOREIGN KEY(SXP_COD_PRATICANTE) REFERENCES PRATICANTE(PRAT_ID)
);

CREATE TABLE SESSAOXFUNCIONARIO (
	SXF_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SXF_COD_SESSAO INTEGER NOT NULL,
    SXF_COD_FUNCIONARIO INTEGER NOT NULL,
	CONSTRAINT FK_SXF_REF_SESSAO FOREIGN KEY(SXF_COD_SESSAO) REFERENCES SESSAO(SES_ID)  ON DELETE CASCADE,
    CONSTRAINT FK_SXF_REF_FUNCIONARIO FOREIGN KEY(SXF_COD_FUNCIONARIO) REFERENCES FUNCIONARIO(FUNC_ID)
);

CREATE TABLE SESSAOXMATERIAL (
	SXM_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SXM_COD_SESSAO INTEGER NOT NULL,
    SXM_COD_MATERIAL INTEGER NOT NULL,
	CONSTRAINT FK_SXM_REF_SESSAO FOREIGN KEY(SXM_COD_SESSAO) REFERENCES SESSAO(SES_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SXM_REF_MATERIAL FOREIGN KEY(SXM_COD_MATERIAL) REFERENCES MATERIAL(MAT_ID)
);

CREATE TABLE SESSAOXANIMALXATIVIDADE (
	SXA_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SXA_COD_SESSAO INTEGER NOT NULL,
    SXA_COD_ANIMAL INTEGER NOT NULL,
    SXA_COD_ATIVIDADE INTEGER NOT NULL,
	CONSTRAINT FK_SXA_REF_SESSAO FOREIGN KEY(SXA_COD_SESSAO) REFERENCES SESSAO(SES_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SXA_REF_ANIMAL FOREIGN KEY(SXA_COD_ANIMAL) REFERENCES ANIMAL(ANI_ID),
	CONSTRAINT FK_SXA_ATIVIDADE FOREIGN KEY(SXA_COD_ATIVIDADE) REFERENCES ATIVIDADE(ATV_ID)
);